name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
          pip install pytest

     #  Authenticate with GCP
      - name: Set up GCP credentials
        env:
          GCS_KEY: ${{ secrets.GCP_CREDENTIALS_B64 }}
        run: |
          # Decode the base64-encoded secret to a JSON file
          echo "$GCS_KEY" | base64 --decode > gcp-key.json
          # Set environment variable for Google SDK
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
          # Authenticate with gcloud
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project mlops-466312
          echo "✓ Authenticated with GCP"

      #  Pull DVC-tracked data from GCS
      - name: Pull DVC data
        run: |
          dvc remote modify gcsremote credentialpath $(pwd)/gcp-key.json
          dvc pull -v
      # Run evaluation/tests
      - name: Run evaluation/tests
        run: pytest week-4/tests/ -v --junitxml=report.xml

      # Post results as PR comment using CML
      - name: Post results as PR comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml-send-comment report.xml || echo "No report generated"
