name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      # Pull DVC tracked data
      - name: Pull DVC tracked data
        env:
          DVC_GCS_CREDENTIALS_JSON: ${{ secrets.GCS_CREDENTIALS_JSON }}
        run: |
          dvc remote modify --local gcsremote gcs_credentials_path $GCS_KEY
          dvc pull

      # Run evaluation/tests
      - name: Run evaluation/tests
        run: pytest week-4/tests/ -v --junitxml=report.xml

      # Post results as PR comment using CML
      - name: Post results as PR comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml-send-comment report.xml || echo "No report generated"
